/**
 * observatory.js
 * "Blue Economy Observatory" data layer — powers the headline stat tiles and
 * hand-drawn charts on insights.html and the homepage #insights teaser.
 *
 * Three-layer resilience so the section never renders empty:
 *   1. Live fetch straight from the Eurostat dissemination API (no API key;
 *      CORS is open — verified: Access-Control-Allow-Origin: *).
 *   2. Fall back to the committed snapshot, assets/data/observatory.json
 *      (regenerated by scripts/fetch-eurostat.sh).
 *   3. Fall back to the constants below — the same real, verified figures,
 *      inlined so even a fully offline/local file load still renders
 *      something correct.
 *
 * Numbers are written to [data-count] so the EXISTING count-up animator in
 * main.js (the cObs IntersectionObserver) animates them — this script does
 * not run its own number tween, it only supplies fresh values before the
 * observer fires (and re-syncs text directly if a tile already finished).
 *
 * Datasets: mar_go_qm (quarterly goods, IN+OUT), mar_sg_am_cw (short-sea
 * shipping, country level). See scripts/fetch-eurostat.sh for the exact
 * queries and data-section.md for background.
 */
(function () {
  var API = 'https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data';
  var SNAPSHOT_URL = 'assets/data/observatory.json';
  var FETCH_TIMEOUT = 6000;

  // Last-resort, zero-network fallback — mirrors the committed snapshot's
  // real, live-verified values (see assets/data/observatory.json "source"
  // fields for exact Eurostat query provenance).
  var HARDCODED_FALLBACK = {
    stats: {
      'total-goods':     { value: 837.1, suffix: ' Mt',   label: 'Goods handled at EU main ports — 2025-Q4', delta: '+1.9% year-on-year' },
      'shortsea-share':  { value: 58.3,  suffix: '%',     label: 'Share of EU maritime freight carried by short-sea shipping — 2024', delta: '+1.8pp vs 2023 (56.5%)' },
      'shortsea-volume': { value: 1.65,  suffix: ' Bn t',  label: 'EU short-sea shipping volume — 2024', delta: null }
    },
    countries: {
      title: 'Top short-sea shipping nations, 2024',
      footnote: 'Italy, the Netherlands and Spain together handled 46.3% of all EU short-sea shipping tonnage in 2024.',
      items: [
        { name: 'Italy', value: 304.1 },
        { name: 'Netherlands', value: 238.8 },
        { name: 'Spain', value: 220.9 }
      ]
    },
    modeShare: { shortSea: 58.3, other: 41.7 },
    retrieved: '2026-07-27'
  };

  var LITE = (function () {
    var c = navigator.connection || {};
    return !!(c.saveData || /(^|\b)(slow-)?2g$/.test(c.effectiveType || ''));
  })();
  var REDUCED_MOTION = window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  var SKIP_DRAW_IN = LITE || REDUCED_MOTION;

  function withTimeout(promise, ms) {
    var ctrl = new AbortController();
    var t = setTimeout(function () { ctrl.abort(); }, ms);
    return { signal: ctrl.signal, run: promise(ctrl.signal).finally(function () { clearTimeout(t); }) };
  }

  function fetchJSON(url, signal) {
    return fetch(url, { signal: signal }).then(function (r) {
      if (!r.ok) throw new Error('HTTP ' + r.status + ' for ' + url);
      return r.json();
    });
  }

  /* ── Live Eurostat fetch, mirrors scripts/fetch-eurostat.sh's logic ── */
  function fetchLive(signal) {
    var goodsUrl = API + '/mar_go_qm?format=JSON&lang=EN&rep_mar=EU27_2020&direct=IN&direct=OUT&tra_cov=TOTAL&unit=THS_T&lastTimePeriod=8';
    var sssUrl   = API + '/mar_sg_am_cw?format=JSON&lang=EN&rep_mar=EU27_2020&seaship=SSS&lastTimePeriod=2';

    return Promise.all([fetchJSON(goodsUrl, signal), fetchJSON(sssUrl, signal)]).then(function (r) {
      var goods = r[0], sss = r[1];

      // ── goods: latest quarter with both IN and OUT present, vs same quarter prior year ──
      var d = goods.dimension.direct.category.index;
      var t = goods.dimension.time.category.index;
      var tsize = goods.size[5];
      var v = goods.value;
      var timeEntries = Object.keys(t).map(function (k) { return { key: k, idx: t[k] }; })
        .sort(function (a, b) { return b.idx - a.idx; });
      var latest = null;
      for (var i = 0; i < timeEntries.length; i++) {
        var e = timeEntries[i];
        var inV = v[(d.IN * tsize) + e.idx], outV = v[(d.OUT * tsize) + e.idx];
        if (inV != null && outV != null) { latest = { key: e.key, inV: inV, outV: outV }; break; }
      }
      if (!latest) throw new Error('no complete quarter in mar_go_qm response');
      var m = latest.key.match(/^(\d{4})-Q(\d)$/);
      var prevKey = (parseInt(m[1], 10) - 1) + '-Q' + m[2];
      var prevIdx = t[prevKey];
      var goodsTotalKt = latest.inV + latest.outV;
      var goodsYoy = null;
      if (prevIdx !== undefined) {
        var prevIn = v[(d.IN * tsize) + prevIdx], prevOut = v[(d.OUT * tsize) + prevIdx];
        if (prevIn != null && prevOut != null) {
          var prevTotal = prevIn + prevOut;
          goodsYoy = ((goodsTotalKt - prevTotal) / prevTotal) * 100;
        }
      }

      // ── short-sea EU share + volume, latest vs previous year ──
      var u2 = sss.dimension.unit.category.index;
      var t2 = sss.dimension.time.category.index;
      var tsize2 = sss.size[4];
      var v2 = sss.value;
      var years = Object.keys(t2).map(function (k) { return { key: k, idx: t2[k] }; }).sort(function (a, b) { return b.idx - a.idx; });
      var latestYear = years[0].key, prevYear = years[1] ? years[1].key : null;
      var volumeKt = v2[(u2.THS_T * tsize2) + t2[latestYear]];
      var shareLatest = v2[(u2.PC_TOT * tsize2) + t2[latestYear]];
      var sharePrev = prevYear != null ? v2[(u2.PC_TOT * tsize2) + t2[prevYear]] : null;

      // ── country breakdown, same latest year ──
      var countryUrl = API + '/mar_sg_am_cw?format=JSON&lang=EN&rep_mar=IT&rep_mar=NL&rep_mar=ES&seaship=SSS&unit=THS_T&time=' + latestYear;
      return fetchJSON(countryUrl, signal).then(function (c) {
        var r3 = c.dimension.rep_mar.category.index;
        var v3 = c.value;
        var IT = v3[String(r3.IT)], NL = v3[String(r3.NL)], ES = v3[String(r3.ES)];
        var top3Kt = IT + NL + ES;

        return {
          stats: {
            'total-goods': {
              value: Math.round((goodsTotalKt / 1000) * 10) / 10,
              suffix: ' Mt',
              label: 'Goods handled at EU main ports — ' + latest.key,
              delta: goodsYoy == null ? null : (goodsYoy >= 0 ? '+' : '') + (Math.round(goodsYoy * 10) / 10) + '% year-on-year'
            },
            'shortsea-share': {
              value: shareLatest,
              suffix: '%',
              label: 'Share of EU maritime freight carried by short-sea shipping — ' + latestYear,
              delta: sharePrev == null ? null : ((shareLatest - sharePrev) >= 0 ? '+' : '') + (Math.round((shareLatest - sharePrev) * 10) / 10) + 'pp vs ' + prevYear + ' (' + sharePrev + '%)'
            },
            'shortsea-volume': {
              value: Math.round((volumeKt / 1000000) * 100) / 100,
              suffix: ' Bn t',
              label: 'EU short-sea shipping volume — ' + latestYear,
              delta: null
            }
          },
          countries: {
            title: 'Top short-sea shipping nations, ' + latestYear,
            footnote: 'Italy, the Netherlands and Spain together handled ' + (Math.round((top3Kt / volumeKt) * 1000) / 10) + '% of all EU short-sea shipping tonnage in ' + latestYear + '.',
            items: [
              { name: 'Italy', value: Math.round(IT / 100) / 10 },
              { name: 'Netherlands', value: Math.round(NL / 100) / 10 },
              { name: 'Spain', value: Math.round(ES / 100) / 10 }
            ]
          },
          modeShare: { shortSea: shareLatest, other: Math.round((100 - shareLatest) * 10) / 10 },
          retrieved: new Date().toISOString().slice(0, 10)
        };
      });
    });
  }

  /* ── snapshot fallback: shape assets/data/observatory.json to the same internal shape ── */
  function normalizeSnapshot(j) {
    var stats = {};
    (j.stats || []).forEach(function (s) { stats[s.id] = { value: s.value, suffix: s.suffix, label: s.label, delta: s.delta || null }; });
    return {
      stats: stats,
      countries: { title: j.countries.title, footnote: j.countries.footnote, items: j.countries.items },
      modeShare: j.modeShare,
      retrieved: j.meta && j.meta.retrieved
    };
  }

  function loadData() {
    var live = withTimeout(function (signal) { return fetchLive(signal); }, FETCH_TIMEOUT);
    return live.run.catch(function (err) {
      console.warn('[observatory] live Eurostat fetch failed, falling back to snapshot:', err.message || err);
      return fetchJSON(SNAPSHOT_URL).then(normalizeSnapshot);
    }).catch(function (err) {
      console.warn('[observatory] snapshot fetch failed, using inline fallback:', err.message || err);
      return HARDCODED_FALLBACK;
    });
  }

  /* ── apply data to the DOM ── */
  function fmt(n) {
    return Number(n).toLocaleString('en-US', { maximumFractionDigits: 2 });
  }

  function applyStats(data) {
    document.querySelectorAll('[data-obs-stat]').forEach(function (el) {
      var s = data.stats[el.dataset.obsStat];
      if (!s) return;
      el.dataset.count = s.value;
      el.dataset.suffix = s.suffix;
      // Re-sync text directly too, in case the count-up already ran (or will
      // never run — e.g. below the fold and the user never scrolls there).
      el.textContent = fmt(s.value) + s.suffix;
    });
    document.querySelectorAll('[data-obs-delta]').forEach(function (el) {
      var s = data.stats[el.dataset.obsDelta];
      if (s && s.delta) el.textContent = s.delta;
      else if (s) el.style.display = 'none';
    });
    document.querySelectorAll('[data-obs-chart-note="countries"]').forEach(function (el) {
      if (data.countries.footnote) el.textContent = data.countries.footnote;
    });
    document.querySelectorAll('[data-obs-chart-title="countries"]').forEach(function (el) {
      if (data.countries.title) el.textContent = data.countries.title;
    });
    document.querySelectorAll('[data-obs-retrieved]').forEach(function (el) {
      if (data.retrieved) {
        var d = new Date(data.retrieved + 'T00:00:00Z');
        el.textContent = isNaN(d) ? data.retrieved : d.toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric', timeZone: 'UTC' });
      }
    });
  }

  /* ── canvas chart drawing — engraved-chart visual language (see js/canvas.js) ── */
  function sizeCanvas(canvas) {
    var dpr = window.devicePixelRatio || 1;
    var cssW = canvas.clientWidth || canvas.parentElement.clientWidth;
    var cssH = Math.round(cssW * (360 / 640));
    canvas.style.height = cssH + 'px';
    canvas.width = Math.round(cssW * dpr);
    canvas.height = Math.round(cssH * dpr);
    var ctx = canvas.getContext('2d');
    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    return { ctx: ctx, w: cssW, h: cssH };
  }

  function drawGraticule(ctx, w, h) {
    ctx.strokeStyle = 'rgba(200,145,58,.08)';
    ctx.lineWidth = 1;
    for (var x = 0; x < w; x += 40) { ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, h); ctx.stroke(); }
    for (var y = 0; y < h; y += 40) { ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(w, y); ctx.stroke(); }
  }

  function drawBarChart(canvas, items) {
    var dim = sizeCanvas(canvas), ctx = dim.ctx, w = dim.w, h = dim.h;
    var padL = 46, padR = 16, padT = 16, padB = 34;
    var chartW = w - padL - padR, chartH = h - padT - padB;
    var max = Math.max.apply(null, items.map(function (i) { return i.value; })) * 1.15;
    var barGap = chartW / items.length;
    var barW = Math.min(70, barGap * 0.5);

    function frame(progress) {
      ctx.clearRect(0, 0, w, h);
      drawGraticule(ctx, w, h);

      // baseline + axis
      ctx.strokeStyle = 'rgba(239,242,241,.25)';
      ctx.lineWidth = 1;
      ctx.beginPath(); ctx.moveTo(padL, padT); ctx.lineTo(padL, h - padB); ctx.lineTo(w - padR, h - padB); ctx.stroke();

      // y-axis ticks
      ctx.font = '10px Barlow Condensed,sans-serif';
      ctx.fillStyle = 'rgba(239,242,241,.4)';
      ctx.textAlign = 'right';
      for (var g = 0; g <= 4; g++) {
        var val = (max / 4) * g;
        var y = h - padB - (chartH * (g / 4));
        ctx.fillText(Math.round(val), padL - 8, y + 3);
        ctx.strokeStyle = 'rgba(239,242,241,.06)';
        ctx.beginPath(); ctx.moveTo(padL, y); ctx.lineTo(w - padR, y); ctx.stroke();
      }

      items.forEach(function (item, i) {
        var barH = (item.value / max) * chartH * progress;
        var x = padL + barGap * i + (barGap - barW) / 2;
        var y = h - padB - barH;
        var grad = ctx.createLinearGradient(0, y, 0, h - padB);
        grad.addColorStop(0, '#e8b870');
        grad.addColorStop(1, '#b8894a');
        ctx.fillStyle = grad;
        ctx.fillRect(x, y, barW, barH);

        ctx.fillStyle = 'rgba(239,242,241,.85)';
        ctx.textAlign = 'center';
        ctx.font = '600 12px Cormorant Garamond,serif';
        if (progress > 0.85) ctx.fillText(item.value.toFixed(1), x + barW / 2, y - 8);

        ctx.font = '10px Barlow Condensed,sans-serif';
        ctx.fillStyle = 'rgba(239,242,241,.55)';
        ctx.fillText(item.name, x + barW / 2, h - padB + 16);
      });
    }

    if (SKIP_DRAW_IN) { frame(1); return; }
    var start = null, dur = 700;
    function step(ts) {
      if (!start) start = ts;
      var p = Math.min((ts - start) / dur, 1);
      frame(1 - Math.pow(1 - p, 3));
      if (p < 1) requestAnimationFrame(step);
    }
    requestAnimationFrame(step);
  }

  function drawShareChart(canvas, shortSea, other) {
    var dim = sizeCanvas(canvas), ctx = dim.ctx, w = dim.w, h = dim.h;
    var barH = 54, y = h / 2 - barH / 2;
    var padX = 16;
    var trackW = w - padX * 2;

    function frame(progress) {
      ctx.clearRect(0, 0, w, h);
      drawGraticule(ctx, w, h);

      ctx.strokeStyle = 'rgba(239,242,241,.2)';
      ctx.strokeRect(padX, y, trackW, barH);

      var sssW = trackW * (shortSea / 100) * progress;
      var grad = ctx.createLinearGradient(padX, 0, padX + sssW, 0);
      grad.addColorStop(0, '#b8894a');
      grad.addColorStop(1, '#e8b870');
      ctx.fillStyle = grad;
      ctx.fillRect(padX, y, sssW, barH);

      ctx.fillStyle = 'rgba(200,145,58,.14)';
      ctx.fillRect(padX + sssW, y, trackW * progress - sssW, barH);

      if (progress > 0.9) {
        ctx.font = '700 20px Cormorant Garamond,serif';
        ctx.fillStyle = '#050c15';
        ctx.textAlign = 'left';
        if (sssW > 70) ctx.fillText(shortSea + '%', padX + 12, y + barH / 2 + 7);
        ctx.fillStyle = 'rgba(239,242,241,.85)';
        ctx.font = '10px Barlow Condensed,sans-serif';
        ctx.fillText('SHORT-SEA', padX + 12, y - 10);

        ctx.textAlign = 'right';
        ctx.fillStyle = 'rgba(239,242,241,.7)';
        ctx.font = '700 16px Cormorant Garamond,serif';
        ctx.fillText(other + '%', w - padX - 12, y + barH / 2 + 6);
        ctx.font = '10px Barlow Condensed,sans-serif';
        ctx.fillText('OTHER / DEEP-SEA', w - padX - 12, y - 10);
      }
    }

    if (SKIP_DRAW_IN) { frame(1); return; }
    var start = null, dur = 700;
    function step(ts) {
      if (!start) start = ts;
      var p = Math.min((ts - start) / dur, 1);
      frame(1 - Math.pow(1 - p, 3));
      if (p < 1) requestAnimationFrame(step);
    }
    requestAnimationFrame(step);
  }

  function applyCharts(data) {
    var barCanvas = document.getElementById('obs-bar-canvas');
    var shareCanvas = document.getElementById('obs-share-canvas');
    if (barCanvas) drawBarChart(barCanvas, data.countries.items);
    if (shareCanvas) drawShareChart(shareCanvas, data.modeShare.shortSea, data.modeShare.other);

    var redraw = function () {
      if (barCanvas) drawBarChart(barCanvas, data.countries.items);
      if (shareCanvas) drawShareChart(shareCanvas, data.modeShare.shortSea, data.modeShare.other);
    };
    var t;
    window.addEventListener('resize', function () {
      clearTimeout(t);
      t = setTimeout(redraw, 200);
    });
  }

  function init() {
    if (!document.querySelector('[data-obs-stat]') && !document.getElementById('obs-bar-canvas')) return; // nothing on this page
    loadData().then(function (data) {
      applyStats(data);
      applyCharts(data);
    });
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
